services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - healthcheck
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Simple health check service to ensure dependencies are ready
  healthcheck:
    image: busybox:latest
    command: ["sh", "-c", "echo 'Health check service ready'"]
    restart: "no"

networks:
  default:
    name: stubborn-chatbot-network
